### ISSUE TITLE
Joust size

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#104]
Based on this image:
![image](https://user-images.githubusercontent.com/8068749/216769947-fe189027-5dd3-4cd4-8c3f-6ff93e551e2f.png)
Increase Joust's height by 10cm.
Flyers on internet said nothing about the cabinet measures.

**Comment by WilsonBradley** [comment]
Great news!

**Comment by curif** [comment]
closed v0.2.0-RC5
