### ISSUE TITLE
Player pass through NPCs

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#108]
Player pass through NPCs in place of push them.

**Comment by WilsonBradley** [comment]
Players should push them and they go away. If not, they will stay in place/overlap you while you are playing. 
As per video

**Comment by curif** [comment]
NPC takes the same position as the player, even when the player is playing.

**Comment by curif** [comment]
Push a NPC isn't possible bcz they are controlled by the navigation IA. But a change of path is possible.
