### ISSUE TITLE
In game environment FX volume (not Arcade games) to loud and not able to control

### ISSUE THREAD

**Issue by WilsonBradley** [curif/AgeOfJoy-2022.1#18]

**Comment by WilsonBradley** [comment]
The sounds are not dynamic and are more static. 
Examples; 
Volume is the same for games in room regardless of how close to cabinet
Background sounds/music also static

Seems the only way to address is to create separate audio channels to have specific volume control

**Comment by curif** [comment]
Volume audio is tuned to the distance between the player and the screen, starting in v0.2.0. That means that the sound should be louder if you are close to the screen.

Right now is a bit lower, I'm working to understand why. You must be quite close to the screen to ear some games.

We should have three channels:

* Ambient noise
* Games (and video) 
* Player music (using a Jukebox)

I'm balancing the first two.
