### ISSUE TITLE
door not opening

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#249]
ChrisMulster
(rc17) did a fresh install did a walk before i added any cabinets having the same problem as on rc15 going from **room 3 to 4** door not opening most of the time can teleport to the room no problem

**Comment by WilsonBradley** [comment]
I also had this problem. Thought Fabio disabled those Room intentionally.

**Comment by curif** [comment]
I think the problem is that the game is not detecting correctly when the player passes through the (invisible) zone to activate the door. I made the zone bigger so it would be easier for the program to react and open the door. It will be available on the next release candidate.
