### ISSUE TITLE
NPCs behavior

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#27]
The NPCs are expected to flee from the user rather than follow or face it.

https://github.com/curif/AgeOfJoy-2022.1/blob/85eb13de85339895f6db386bce054134de62111f/Assets/curif/LibRetroWrapper/ArcadeRoomBehaviour.cs#L129

**Comment by WilsonBradley** [comment]
This will be good.. Those characters were annoying & and some creepy.. lol
