### ISSUE TITLE
Possible to add a Feature request section? 

### ISSUE THREAD

**Issue by WilsonBradley** [curif/AgeOfJoy-2022.1#4]
Possible to add a Feature request section/ Discussion section in this channel? 

Tanx

**Comment by WilsonBradley** [comment]
Also, iv'e seen other Github channels have some type of Discussions tab. This would help keep things organized from start. 
Example, you wouldn't want folks posting everything under Issues .
Thanks for all you do BTW..
Following

**Comment by curif** [comment]
Done!
Thank you.
