### ISSUE TITLE
Stupid Questions..

### ISSUE THREAD

**Issue by WilsonBradley** [curif/AgeOfJoy-2022.1#5]
I guess for the files on here, I would need to install a Android compiler? 
I did not find a APK. 

Thanks

**Comment by WilsonBradley** [comment]
I think compiled files / APK's can be posted in Package section. 
[Packages](https://github.com/users/curif/packages?repo_name=AgeOfJoy-2022.1)

**Comment by WilsonBradley** [comment]
example;
Under Releases section;
https://github.com/vpinball/vpinball

**Comment by curif** [comment]
You can find the apk, announcements, posts, etc in the [itchio page](https://curifab.itch.io/age-of-joy).

IMHO itchio is a better tool for users who don't understand (and don't need to) anything about development or GitHub. Also AGE of Joy has its own page in Sidequest.
