### ISSUE TITLE
Video don't start

### ISSUE THREAD

**Issue by curif** [curif/AgeOfJoy-2022.1#65]
Some videos will not start in roms that are overcrowded with cabinets.
It works well in isolation (workshop)

`01-07 19:24:28.282 23507 23635 W Unity   : AndroidVideoMedia: Could not create decoder for mime type video/avc.`

**Comment by curif** [comment]
The number of cabinets has an impact on videos. Quest2 cannot handle a large number of videos.
A better solution is to keep no more than 10 cabinets open at any given time.

**Comment by WilsonBradley** [comment]
yes, noticed this.
Seems the cabinets have to constantly refresh going in/out of rooms.

Sincerely,

Wilson Bradley
***@***.***

**Comment by curif** [comment]
Solved in v0.2.0
