### ISSUE TITLE
The games cannot be started

### ISSUE THREAD

**Issue by lfoproject** [curif/AgeOfJoy-2022.1#77]
Unfortunately I have problems with this version. I uploaded the ROM of each one. I can also see and hear the trailers of the games in the machines. If I insert the coin, I don't get any credits and the games won't start. I've tried everything. Do others have the same problems as me or did I miss something?

**Comment by WilsonBradley** [comment]
This is because the roms are not the exact. 
I believe there is a opensource arcade that you can verify the main app works.
Please look at CRC page for finding roms out in the ocean.
https://curif.notion.site/AGE-of-Joy-Rom-compatibility-Database-a3793cebeb5c4a7f9b1cd2c3306d2ee1

**Comment by curif** [comment]
Please check:

- ROMs are in the `/sdcard/Android/data/com.curif.AgeOfJoy/downloads` folder. They are zip files, you don't need to decompress anything.
- Your ROMs are compatible: please check the md5sum (CRC check) of your ROM, for example for [TimePilot](https://curif.notion.site/AGE-of-Joy-Rom-compatibility-Database-a3793cebeb5c4a7f9b1cd2c3306d2ee1?p=894948449b514ecc846a1519fd280522&pm=s) is `ed897eef2999c1edb72ea13c36d1cd10`. Use [this tool](https://curif.github.io/AgeOfJoy-ROMCRC/index.html) to checkit.
- Concentrate on one game at a time, attempting to solve the problem in that game; as said before, TimePilot is a good place to start.
- Reinstall the cabinet (copying again in `/cabinet` folder) and run again the game, walk to the cabinet, insert a coin, after the load screen (game room boot) wait some seconds waiting for the game to take the coin. If that doesn't work, try again with a coin.

**Comment by curif** [comment]
Great!, you were very lucky back then, you could play the games for free!!!

**Comment by WilsonBradley** [comment]
@lfoproject  Just to clarify, those Cabinet Packs do not contain roms. Just assets for the cabinets of those types of games. The reason why I point this out is, the files within could be mistaken as ROMs example;
![image](https://user-images.githubusercontent.com/8173893/213029258-cba4b575-e971-4068-8649-03d30b0c6fff.png)

**Comment by lfoproject** [comment]
@WilsonBradley many thanks. The tip was great. Now I understood the principle and was able to play the first game. It feels fantastic 👍 It will be time consuming to find the right roms 😊

**Comment by curif** [comment]
Great!!!

btw the asset pack 4 will include moon patrol.

![image](https://user-images.githubusercontent.com/8068749/213311834-e90e482e-5e84-4549-960e-f4a403dc9534.png)

**Comment by lfoproject** [comment]
@curif oh great, the anticipation is rising 😊👍

**Comment by WilsonBradley** [comment]
Yes, patiently waiting....

Sincerely,

Wilson Bradley
***@***.***

**Comment by curif** [comment]
Solved in v0.2.0
