### ISSUE TITLE
Cabinets can sometimes block you from moving to other cabinets

### ISSUE THREAD

**Issue by Elleby77** [curif/AgeOfJoy-2022.1#89]
Sometimes cabinets can block the path to other cabinets.

In this screenshot: https://photos.app.goo.gl/nmsG8aotbRF1ZVxG6 I am unable to walk over to the Tron cabinet as there is not enough room.

In this screenshot https://photos.app.goo.gl/MgtQX4gcbCwVdYvD6 I am unable to access the last four cabinets in the room due to two "donkeykong" style cabinets facing each other and not leaving enough room to pass.

**Comment by curif** [comment]
It's the v0.2.0?

**Comment by WilsonBradley** [comment]
@Fabio Curi ***@***.***>
I doubt it, v0.2.0 hasn't been easily available, unless that recently
changed.

Sincerely,

Wilson Bradley
***@***.***

**Comment by curif** [comment]
As I can see the pictures are from the v0.1.0 (last published in itchio). You can download a release candidate from https://github.com/curif/AgeOfJoy-2022.1/releases/tag/v0.2.0-rc0. I modified some player's parameters in this version that maybe solved the issue.

**Comment by WilsonBradley** [comment]
Thank you!!!
You are becoming a Quest Dev. Legend..

Sincerely,

Wilson Bradley
***@***.***

**Comment by curif** [comment]
it happens in rooms full of closets
.
